export const RETRIEVE_RESULTS = 'RETRIEVE_RESULTS'
export const RETRIEVE_RESULTS_OK = 'RETRIEVE_RESULTS_OK'
export const RETRIEVE_RESULTS_ERROR = 'RETRIEVE_RESULTS_ERROR'

export const RETRIEVE_DETAIL = 'RETRIEVE_DETAIL'
export const RETRIEVE_DETAIL_OK = 'RETRIEVE_DETAIL_OK'
export const RETRIEVE_DETAIL_ERROR = 'RETRIEVE_DETAIL_ERROR'
